#!/usr/bin/env bash
set -euo pipefail
rm -rf dist
mkdir -p dist
mkdir -p bin

echo "build src/pageshot.ls -> dist/pageshot.js ..."
npx lsc -cbp src/pageshot.ls > dist/pageshot.js
echo "build src/server.ls -> dist/server.js ..."
echo "#!/usr/bin/env node" > dist/server.js
npx lsc -cbp src/server.ls >> dist/server.js
echo "done."
